//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFollow.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeles()
        {
            this.Taskes = new HashSet<Taskes>();
        }
    
        public short ID { get; set; }
        public string PersonelName { get; set; }
        public string PersonelSurname { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelPassword { get; set; }
        public string PersonelTel { get; set; }
        public byte[] PersonelPicture { get; set; }
        public byte DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taskes> Taskes { get; set; }
    }
}
