//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFollow.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taskes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taskes()
        {
            this.TaskDetails = new HashSet<TaskDetails>();
        }
    
        public int ID { get; set; }
        public short TaskSender { get; set; }
        public short TaskReceiver { get; set; }
        public string TaskDesc { get; set; }
        public System.DateTime TaskDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Personeles Personeles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDetails> TaskDetails { get; set; }
    }
}
