//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirmaCagri.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyCall()
        {
            this.CallDetails = new HashSet<CallDetails>();
            this.Taskes = new HashSet<Taskes>();
        }
    
        public short ID { get; set; }
        public short CompanyID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public System.DateTime C_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallDetails> CallDetails { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taskes> Taskes { get; set; }
    }
}
