//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirmaCagri.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetails
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public string TaskDetailDesc { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
    
        public virtual Taskes Taskes { get; set; }
    }
}
